volumes:
  pg-data:

services:
  postgres:
    container_name: compose-storage-postgres
    image: postgres:16.3-alpine
    env_file: ./../configs/local.env
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always

  service-api:
      container_name: compose-service-api
      build:
        context: ./../
        dockerfile: ./cmd/service-api/Dockerfile
      restart: always
      env_file: ./../configs/local.env
      environment:
        POSTGRES_HOST: "compose-storage-postgres"
        CGO_ENABLED: 1
      ports:
        - "9001:9001"
      depends_on:
        - postgres