volumes:
  pg-data:

services:
  postgres:
    image: postgres:16.3-alpine
    env_file: ./../configs/local.env
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always